[
	{
		"name":"浙江省",
		"children":[
			{
				"name":"杭州市",
				"children":[
					{
						"name":"西湖区",
						"children":[
							{"name":"西湖北线/黄龙"},
							{"name":"龙井/虎跑"},
							{"name":"高新文教区"},
							{"name":"古墩路沿线"},
							{"name":"高新文教区"}
						]
					},
					{
						"name":"上城区",
						"children":[
							{"name":"湖滨"},
							{"name":"南山路"},
							{"name":"吴山广场/河坊街"},
							{"name":"城站火车站"}
						]
					},
					{
						"name":"下城区",
						"children":[
							{"name":"武林广场"},
							{"name":"凤起路沿线"},
							{"name":"庆春路沿线"},
							{"name":"朝晖地区"}
						]
					},
					{
						"name":"拱墅区",
						"children":[
							{"name":"湖墅南路"},
							{"name":"大关"},
							{"name":"拱宸桥/上塘"},
							{"name":"朝晖地区"}
						]
					},
					{
						"name":"江干区",
						"children":[
							{"name":"城东"},
							{"name":"下沙"}
						]
					},
					{
						"name":"萧山区",
						"children":[
							{"name":"城厢"},
							{"name":"北干"},
							{"name":"萧山其他"}
						]
					},
					{
						"name":"滨江区",
						"children":[
							{"name":"开发区/高教园"}
						]
					}
				]
			}
		]
	}
]