[
	{
		"name":"美食",
		"children":[

                        {"name":"地方菜"},
			{"name":"特色小吃"},
			{"name":"火锅"},
			{"name":"烧烤"},
			{"name":"中式快餐"},
			{"name":"西餐"},
			{"name":"日韩料理"},
			{"name":"西式快餐"},
			{"name":"蛋糕甜点"},
			{"name":"其他"}
		]
	},
	{
		"name":"购物",
		"children":[
		    {"name":"服饰"},
		    {"name":"数码"},
	            {"name":"超市"},
		    {"name":"眼镜"},
                    {"name":"书籍"}
		]
	},
	{
		"name":"生活相关",
		"children":[
		    {"name":"美发"},
		    {"name":"医院"},
		    {"name":"药店"},
                    {"name":"住宿"},
                    {"name":"写真"},
                    {"name":"健身"},
                    {"name":"美容"},
                    {"name":"培训"},
                    {"name":"其他"}
		]
	},
	{
		"name":"休闲娱乐",
		"children":[
		    {"name":"KTV"},
                    {"name":"电影院"},
	            {"name":"桌游"},
	            {"name":"旅游"},
		    {"name":"其他"}
		]
	}
]